services:
  mongo:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  #     - mcp-server

  # mcp-server:
  #   build: ./mcp-servers
  #   ports:
  #     - "8001:8001"

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: